export class Model {
  component = {
    NbpAuthComponent: {
      textInput: {
        label: "Username",
        name: "username",
        required: "true",
        requiredMessage: "The username is required",
        placeholder: "Insert your username",
        icon: "fa fa-user",
      },
      passwordInput: {
        label: "Password",
        label2: "New password",
        label3: "Old password",
        name: "password",
        required: "true",
        requiredMessage: "The password is required",
        placeholder: "Insert your password",
        hidePassword: "fa fa-lock",
        showPassword: "fa fa-unlock",
      },
      confirmPasswordInput: {
        label: "Confirm Password",
        label2: "Confirm New Password",
        name: "confirmPassword",
        required: "true",
        requiredMessage: "The confirm password is required",
        placeholder: "Confirn your password",
        hidePassword: "fa fa-lock",
        showPassword: "fa fa-unlock",
      },
      emailInput: {
        label: "Email",
        name: "email",
        required: "true",
        requiredMessage: "The email is required",
        placeholder: "Insert your email",
        icon: "fa fa-envelope",
      },
      submitInput: {
        login: "Login",
        register: "Register",
        resetPassword: "Reset Password",
        updatePassword: "Update Password",
        showPassword: "Show Password",
        updateProfile: "Update Profile",
        back: "Back to Home",
        success: "Go to Login Page"
      },
      newUser: "New User?",
      alreadyUser: "Already have an account?"
    },
    NbpBoxeComponent: {
      boxes: [
        {
          title: "Text Boxe One",
          description:
            "Lorem Ipsum is simply dummy text of the printing and typesetting industry.Lorem Ipsum has been the industry standard dummy text ever since the s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry standard dummy text ever since the s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry standard dummy text ever since the s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry standard dummy text ever since the s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry standard dummy text ever since the s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry standard dummy text ever since the s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry standard dummy text ever since the s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry standard dummy text ever since the s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry standard dummy text ever since the s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry standard dummy text ever since the s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry standard dummy text ever since the s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
          date: "2020-06-08T12:07:33.291",
          image: "/assets/images/nbp-boxes/image-1.png",
          url: "https://www.google.com",
        },
        {
          title: "Text Boxe Two",
          description:
            "Lorem Ipsum is simply dummy text of the printing and typesetting industry.Lorem Ipsum has been the industry standard dummy text ever since the s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry standard dummy text ever since the s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry standard dummy text ever since the s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry standard dummy text ever since the s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry standard dummy text ever since the s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry standard dummy text ever since the s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry standard dummy text ever since the s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry standard dummy text ever since the s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry standard dummy text ever since the s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry standard dummy text ever since the s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry standard dummy text ever since the s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
          date: "2019-05-23T09:34:20.291",
          image: "/assets/images/nbp-boxes/image-2.png",
          url: "https://www.facebook.com",
        },
        {
          title: "Text Boxe Three",
          description:
            "Lorem Ipsum is simply dummy text of the printing and typesetting industry.Lorem Ipsum has been the industry standard dummy text ever since the s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry standard dummy text ever since the s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry standard dummy text ever since the s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry standard dummy text ever since the s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry standard dummy text ever since the s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry standard dummy text ever since the s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry standard dummy text ever since the s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry standard dummy text ever since the s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry standard dummy text ever since the s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry standard dummy text ever since the s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry standard dummy text ever since the s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
          date: "2020-11-11T09:34:20.291",
          image: "/assets/images/nbp-boxes/image-3.png",
          url: "https://www.yahoo.com",
        },
        {
          title: "Text Boxe Fourth",
          description:
            "Lorem Ipsum is simply dummy text of the printing and typesetting industry.Lorem Ipsum has been the industry standard dummy text ever since the s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry standard dummy text ever since the s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry standard dummy text ever since the s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry standard dummy text ever since the s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry standard dummy text ever since the s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry standard dummy text ever since the s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry standard dummy text ever since the s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry standard dummy text ever since the s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry standard dummy text ever since the s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry standard dummy text ever since the s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry standard dummy text ever since the s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
          date: "2021-12-11T09:34:20.291",
          image: "/assets/images/nbp-boxes/image-4.png",
          url: "https://www.twitter.com",
        },
      ],
    },
    NbpInputSwitchOneComponent: {
      one: {
        default: "default-one",
        info: "info-one",
        danger: "danger-one",
        warning: "warning-one",
        black: "black-one",
        primary: "primary-one",
        tomato: "tomato-one",
        smoke: "smoke-one",
        success: "success-one",
      },
      two: {
        default: "default-two",
        info: "info-two",
        danger: "danger-two",
        warning: "warning-two",
        black: "black-two",
        primary: "primary-two",
        tomato: "tomato-two",
        smoke: "smoke-two",
        success: "success-two",
      },
      three: {
        default: "default-three",
        info: "info-three",
        danger: "danger-three",
        warning: "warning-three",
        black: "black-three",
        primary: "primary-three",
        tomato: "tomato-three",
        smoke: "smoke-three",
        success: "success-three",
      },
      fourth: {
        default: "default-fourth",
        info: "info-fourth",
        danger: "danger-fourth",
        warning: "warning-fourth",
        black: "black-fourth",
        primary: "primary-fourth",
        tomato: "tomato-fourth",
        smoke: "smoke-fourth",
        success: "success-fourth",
      },
    },
    NbpCardComponent: {
      title: "Card Title 1",
      description:
        "Si vous poursuivez la navigation, nous utiliserons les cookies qui amélioreront les performances de notre site et personnaliseront votre expérience. Si vous acceptez, nous utiliserons également les cookies pour personnaliser les publicités.",
      titleCta1: "Add money",
      titleCta2: "Go shopping",
      titleCta3: "Visit store",
    },
    NbpCookieComponent: {
      title: "Accept the Cookies",
      text:
        "Si vous poursuivez la navigation, nous utiliserons les cookies qui amélioreront les performances de notre site et personnaliseront votre expérience. Si vous acceptez, nous utiliserons également les cookies pour personnaliser les publicités.",
      href: "https://www.google.com",
      link: "Gérer vos cookies Accepter",
    },
    NbpLinkPageComponent: {
      name1: "Deep Link",
      name2: "Arrow Link",
      href: "https://www.google.com",
    },
    NbpPanelTitlePageComponent: {
      title: {
        normal: "Panel Title",
        left: "Panel Title Left",
        center: "Panel Title Center",
        right: "Panel title Right",
      },
    },
    NbpBadgeComponent: {
      name: "Badge Name",
      icon: "nbp-icon-user",
    },
    NbpTableComponent: {
      headers: [
        { label: "FIRST_NAME", name: "First Name" },
        { label: "LAST_NAME", name: "Last Name" },
        { label: "EMAIL", name: "Email Adress" },
        { label: "PHONE", name: "Phone Number" },
        { label: "ZIP_CODE", name: "Zip Code" },
        { label: "STREET", name: "Street Discrit" },
      ],
      bodies: [
        {
          firstName: "Mario",
          lastName: "Rossi",
          email: "mario.rossi@gmail.com",
          phone: "85",
          zipCode: "2",
          street: "Viale Romagna 32",
        },
        {
          firstName: "Rosita",
          lastName: "Francesca",
          email: "rosita.francesca@gmail.com",
          phone: "3",
          zipCode: "0",
          street: "Viale Santa Maria ",
        },
        {
          firstName: "Mario",
          lastName: "Rossi",
          email: "mario.rossi@gmail.com",
          phone: "85",
          zipCode: "2",
          street: "Viale Romagna 32",
        },
        {
          firstName: "Rosita",
          lastName: "Francesca",
          email: "rosita.francesca@gmail.com",
          phone: "3",
          zipCode: "0",
          street: "Viale Santa Maria ",
        },
        {
          firstName: "Mario",
          lastName: "Rossi",
          email: "mario.rossi@gmail.com",
          phone: "85",
          zipCode: "2",
          street: "Viale Romagna 32",
        },
        {
          firstName: "Rosita",
          lastName: "Francesca",
          email: "rosita.francesca@gmail.com",
          phone: "3",
          zipCode: "0",
          street: "Viale Santa Maria ",
        },
        {
          firstName: "Mario",
          lastName: "Rossi",
          email: "mario.rossi@gmail.com",
          phone: "85",
          zipCode: "2",
          street: "Viale Romagna 32",
        },
        {
          firstName: "Rosita",
          lastName: "Francesca",
          email: "rosita.francesca@gmail.com",
          phone: "3",
          zipCode: "0",
          street: "Viale Santa Maria ",
        },
        {
          firstName: "Mario",
          lastName: "Rossi",
          email: "mario.rossi@gmail.com",
          phone: "85",
          zipCode: "2",
          street: "Viale Romagna 32",
        },
        {
          firstName: "Rosita",
          lastName: "Francesca",
          email: "rosita.francesca@gmail.com",
          phone: "3",
          zipCode: "0",
          street: "Viale Santa Maria ",
        },
        {
          firstName: "Mario",
          lastName: "Rossi",
          email: "mario.rossi@gmail.com",
          phone: "85",
          zipCode: "2",
          street: "Viale Romagna 32",
        },
        {
          firstName: "Rosita",
          lastName: "Francesca",
          email: "rosita.francesca@gmail.com",
          phone: "3",
          zipCode: "0",
          street: "Viale Santa Maria ",
        },
        {
          firstName: "Mario",
          lastName: "Rossi",
          email: "mario.rossi@gmail.com",
          phone: "85",
          zipCode: "2",
          street: "Viale Romagna 32",
        },
        {
          firstName: "Rosita",
          lastName: "Francesca",
          email: "rosita.francesca@gmail.com",
          phone: "3",
          zipCode: "0",
          street: "Viale Santa Maria ",
        },
        {
          firstName: "Mario",
          lastName: "Rossi",
          email: "mario.rossi@gmail.com",
          phone: "85",
          zipCode: "2",
          street: "Viale Romagna 32",
        },
        {
          firstName: "Rosita",
          lastName: "Francesca",
          email: "rosita.francesca@gmail.com",
          phone: "3",
          zipCode: "0",
          street: "Viale Santa Maria ",
        },
        {
          firstName: "Mario",
          lastName: "Rossi",
          email: "mario.rossi@gmail.com",
          phone: "85",
          zipCode: "2",
          street: "Viale Romagna 32",
        },
        {
          firstName: "Rosita",
          lastName: "Francesca",
          email: "rosita.francesca@gmail.com",
          phone: "3",
          zipCode: "0",
          street: "Viale Santa Maria ",
        },
        {
          firstName: "Mario",
          lastName: "Rossi",
          email: "mario.rossi@gmail.com",
          phone: "85",
          zipCode: "2",
          street: "Viale Romagna 32",
        },
        {
          firstName: "Rosita",
          lastName: "Francesca",
          email: "rosita.francesca@gmail.com",
          phone: "3",
          zipCode: "0",
          street: "Viale Santa Maria ",
        },
        {
          firstName: "Mario",
          lastName: "Rossi",
          email: "mario.rossi@gmail.com",
          phone: "85",
          zipCode: "2",
          street: "Viale Romagna 32",
        },
        {
          firstName: "Rosita",
          lastName: "Francesca",
          email: "rosita.francesca@gmail.com",
          phone: "3",
          zipCode: "0",
          street: "Viale Santa Maria ",
        },
        {
          firstName: "Mario",
          lastName: "Rossi",
          email: "mario.rossi@gmail.com",
          phone: "85",
          zipCode: "2",
          street: "Viale Romagna 32",
        },
        {
          firstName: "Rosita",
          lastName: "Francesca",
          email: "rosita.francesca@gmail.com",
          phone: "3",
          zipCode: "0",
          street: "Viale Santa Maria ",
        },
        {
          firstName: "Mario",
          lastName: "Rossi",
          email: "mario.rossi@gmail.com",
          phone: "85",
          zipCode: "2",
          street: "Viale Romagna 32",
        },
        {
          firstName: "Rosita",
          lastName: "Francesca",
          email: "rosita.francesca@gmail.com",
          phone: "3",
          zipCode: "0",
          street: "Viale Santa Maria ",
        },
        {
          firstName: "Mario",
          lastName: "Rossi",
          email: "mario.rossi@gmail.com",
          phone: "85",
          zipCode: "2",
          street: "Viale Romagna 32",
        },
        {
          firstName: "Rosita",
          lastName: "Francesca",
          email: "rosita.francesca@gmail.com",
          phone: "3",
          zipCode: "0",
          street: "Viale Santa Maria ",
        },
        {
          firstName: "Mario",
          lastName: "Rossi",
          email: "mario.rossi@gmail.com",
          phone: "85",
          zipCode: "2",
          street: "Viale Romagna 32",
        },
        {
          firstName: "Rosita",
          lastName: "Francesca",
          email: "rosita.francesca@gmail.com",
          phone: "3",
          zipCode: "0",
          street: "Viale Santa Maria ",
        },
      ],
    },
    NbpColorComponent: {
      colors: [
        { label: "DEFAULT", name: "Default", code: "#63666a" },
        { label: "TOMATO", name: "Tomato", code: "#d12420" },
        { label: "WHITE", name: "White", code: "#ffffff" },
        { label: "BLACK", name: "Black", code: "#000000" },
        { label: "PRIMARY", name: "Primary", code: "#0a66c2" },
        { label: "SUCCESS", name: "Success", code: "#057642" },
        { label: "WARM_GRAY_20", name: "Warm Gray 20", code: "#f3f2ef" },
        { label: "WARNING", name: "Warning", code: "#fa9600" },
        { label: "DANGER", name: "Danger", code: "#f55854" },
        { label: "INFO", name: "Info", code: "#0096c8" },
        { label: "WHITE_SMOKE", name: "White Smoke", code: "#f2f2f2" },
        { label: "NIGHT_RIDER", name: "Night Rider", code: "#323232" },
        { label: "SLIVER", name: "Sliver", code: "#e0e0e1" },
        { label: "EGYPTIAN_BLUE", name: "Egytian Blue", code: "#f1faff" },
        { label: "FLORAL_WHITE", name: "Floral White", code: "#fffbe9" },
        { label: "MINT_CREAM", name: "Mint Cream", code: "#ddffeb" },
        { label: "MISTY_ROSE", name: "Misty Rose", code: "#ffd6d6" },
      ],
    },
    NbpButtonComponent: {
      label: "Button",
      cerca: "Cerca",
      close: "Close",
      salva: "Salva",
      labelHover: "Button Hover",
      cta: "My Profil",
    },
    NbpDividingLineComponent: {
      nbpTitleCenter: "Dividing Line Text Center",
      nbpTitleLeft: "Dividing Line Text Left",
      nbpTitleRight: "Dividing Line Text Right",
      nbpTitleCtaReadOnly: {
        title: "Dividing Line Composant with Cta read only",
        cta: {
          show: "My Profil",
          hide: "Edit Profil",
        },
      },
      nbpTitleCta: {
        title: "Dividing Line Composant with Cta",
        cta: "Edit Profil",
      },
    },
    NbpBackgroundBoxComponent: {
      title: "Background Box Title",
      subtitle:
        "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    },
    NbpAlertBoxComponent: {
      title:
        "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry standard dummy text ever since the s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    },
    NbpFeedbackComponent: {
      success: "Feedback Success",
      warning: "Feedback Warning",
      errore: "Feedback Errore",
      message:
        "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry standard dummy text ever since the s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    },
    NbpCheckboxComponent: {
      label: "Privacy Policy",
    },
    NbpInputTextComponent: {
      label1: "First Name",
      label2: "Last Name",
      name: "firstName",
      to: "Recipient",
      value: "Mario Rossi",
      required: "true",
      requiredMessage: "The first name is required",
      placeholder: "Insert your name",
      icon1: "fa fa-search",
      icon2: "fa fa-user",
    },
    NbpInputPasswordComponent: {
      label1: "Password",
      label2: "Confirm Password",
      name: "password",
      to: "Recipient",
      value: "Mario Rossi",
      required: "true",
      requiredMessage: "The password is required",
      placeholder: "Insert your password",
      hidePassword: "fa fa-lock",
      showPassword: "fa fa-unlock",
    },
    NbpTextareaComponent: {
      label1: "Description First Name with limit = 10",
      label2: "Description Last Name readonly",
      label3: "Description Name without limit",
      messageModal: "Message",
      rows: 8,
      name: "description",
      required: "true",
      requiredMessage: "The description name is required",
      maxLengthMessage: "You have superate the length required",
      placeholder: "Insert the description name",
      maxLength: 10,
    },
    NbpModalComponent: {
      modalOne: "Modal Top - Static - Scrollable",
      modalTwo: "Modal Top - Static - NoScrollable",
      modalThree: "Modal Center - Static - Scrollable",
      modalFourth: "Modal Center - Static - NoScrollable",
      modal: "modal",
      close: "close",
      save: "Save",
      sendMessage: "Send message",
      modalTitle1: "size MD,position CENTER,Type NOSTATIC,Scrollable",
      modalTitle2: "size MD,position TOP,Type STATIC,No Scrollable",
      modalTitle3: "size LG,position CENTER,Type STATIC,No Scrollable",
      modalTitle4: "size LG,position CENTER,Type NOSTATIC,No Scrollable",
      modalTitle5: "size LG,position TOP,Type NOSTATIC,No Scrollable",
      content: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
      content1: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
      content2: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.Lorem Ipsum has been the industry standard dummy text ever since the s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry standard dummy text ever since the s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry standard dummy text ever since the s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry standard dummy text ever since the s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry standard dummy text ever since the s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry standard dummy text ever since the s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry standard dummy text ever since the s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry standard dummy text ever since the s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry standard dummy text ever since the s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry standard dummy text ever since the s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry standard dummy text ever since the s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    },
    NbpTooltipComponent: {
      hoverLeft: "hover left",
      hoverTop: "hover top",
      clickRight: "clicking over right",
      hoverBottom: "hover bottom",
      showWithDelay: "hover tooltip with show delay 2 secondes",
      hideWithDelay: "hover tooltip with hide delay 3 secondes",
      showWithDelayAndWidth: "click tooltip with hide delay 3 secondes and max width 500",
      content: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
      content1: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
      content2: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.Lorem Ipsum has been the industry standard dummy text ever since the s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry standard dummy text ever since the s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry standard dummy text ever since the s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry standard dummy text ever since the s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry standard dummy text ever since the s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry standard dummy text ever since the s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry standard dummy text ever since the s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry standard dummy text ever since the s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry standard dummy text ever since the s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry standard dummy text ever since the s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry standard dummy text ever since the s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    },
    NbpTabBarComponent: {
      title: [
        {
        name: 'DOSSIERS',
        url:'/composants/tab-bar/dossiers'
      },
      {
        name: 'SETTINGS',
        url:'/composants/tab-bar/setting'
      },
      {
        name: 'LINKS',
        url:'/composants/tab-bar/links'
      },
      {
        name: 'ADDRESS',
        url:'/composants/tab-bar/address'
      },
      {
        name: 'REPORTS',
        url:'/composants/tab-bar/reports'
      },
      {
        name: 'DISABLED',
        url:'/composants/tab-bar/disabled'
      }
    ],
    title2: [
      {
      name: 'CALENDAR',
      icon:'nbp-icon-calendar-minus',
      url:'/composants/tab-bar/calendar'
    },
    {
      name: 'DOCUMENTS',
      icon:'nbp-icon-briefcase',
      url:'/composants/tab-bar/documents'
    },
    {
      name: 'SETTINGS DOC',
      icon:'nbp-icon-bars',
      url:'/composants/tab-bar/settingDoc'
    },
    {
      name: 'USERS ADDRESS',
      icon:'nbp-icon-address-book',
      url:'/composants/tab-bar/usersAddress'
    },
    {
      name: 'BUSSINESS TIME',
      icon:'nbp-icon-business-time',
      url:'/composants/tab-bar/bussiness'
    }
  ]
    },
    NbpIconComponent: {
      icons: [
        { name: "nbp-icon-500px" },
        { name: "nbp-icon-accessible-icon" },
        { name: "nbp-icon-accusoft" },
        { name: "nbp-icon-acquisitions-incorporated" },
        { name: "nbp-icon-ad" },
        { name: "nbp-icon-address-book" },
        { name: "nbp-icon-address-card" },
        { name: "nbp-icon-adjust" },
        { name: "nbp-icon-adn" },
        { name: "nbp-icon-adversal" },
        { name: "nbp-icon-affiliatetheme" },
        { name: "nbp-icon-air-freshener" },
        { name: "nbp-icon-airbnb" },
        { name: "nbp-icon-algolia" },
        { name: "nbp-icon-align-center" },
        { name: "nbp-icon-align-justify" },
        { name: "nbp-icon-align-left" },
        { name: "nbp-icon-align-right" },
        { name: "nbp-icon-alipay" },
        { name: "nbp-icon-allergies" },
        { name: "nbp-icon-amazon" },
        { name: "nbp-icon-amazon-pay" },
        { name: "nbp-icon-ambulance" },
        { name: "nbp-icon-american-sign-language-interpreting" },
        { name: "nbp-icon-amilia" },
        { name: "nbp-icon-anchor" },
        { name: "nbp-icon-android" },
        { name: "nbp-icon-angellist" },
        { name: "nbp-icon-angle-double-down" },
        { name: "nbp-icon-angle-double-left" },
        { name: "nbp-icon-angle-double-right" },
        { name: "nbp-icon-angle-double-up" },
        { name: "nbp-icon-angle-down" },
        { name: "nbp-icon-angle-left" },
        { name: "nbp-icon-angle-right" },
        { name: "nbp-icon-angle-up" },
        { name: "nbp-icon-angry" },
        { name: "nbp-icon-angrycreative" },
        { name: "nbp-icon-angular" },
        { name: "nbp-icon-ankh" },
        { name: "nbp-icon-app-store" },
        { name: "nbp-icon-app-store-ios" },
        { name: "nbp-icon-apper" },
        { name: "nbp-icon-apple" },
        { name: "nbp-icon-apple-alt" },
        { name: "nbp-icon-apple-pay" },
        { name: "nbp-icon-archive" },
        { name: "nbp-icon-archway" },
        { name: "nbp-icon-arrow-alt-circle-down" },
        { name: "nbp-icon-arrow-alt-circle-left" },
        { name: "nbp-icon-arrow-alt-circle-right" },
        { name: "nbp-icon-arrow-alt-circle-up" },
        { name: "nbp-icon-arrow-circle-down" },
        { name: "nbp-icon-arrow-circle-left" },
        { name: "nbp-icon-arrow-circle-right" },
        { name: "nbp-icon-arrow-circle-up" },
        { name: "nbp-icon-arrow-down" },
        { name: "nbp-icon-arrow-left" },
        { name: "nbp-icon-arrow-right" },
        { name: "nbp-icon-arrow-up" },
        { name: "nbp-icon-arrows-alt" },
        { name: "nbp-icon-arrows-alt-h" },
        { name: "nbp-icon-arrows-alt-v" },
        { name: "nbp-icon-artstation" },
        { name: "nbp-icon-assistive-listening-systems" },
        { name: "nbp-icon-asterisk" },
        { name: "nbp-icon-asymmetrik" },
        { name: "nbp-icon-at" },
        { name: "nbp-icon-atlas" },
        { name: "nbp-icon-atlassian" },
        { name: "nbp-icon-atom" },
        { name: "nbp-icon-audible" },
        { name: "nbp-icon-audio-description" },
        { name: "nbp-icon-autoprefixer" },
        { name: "nbp-icon-avianex" },
        { name: "nbp-icon-aviato" },
        { name: "nbp-icon-award" },
        { name: "nbp-icon-aws" },
        { name: "nbp-icon-baby" },
        { name: "nbp-icon-baby-carriage" },
        { name: "nbp-icon-backspace" },
        { name: "nbp-icon-backward" },
        { name: "nbp-icon-bacon" },
        { name: "nbp-icon-bacteria" },
        { name: "nbp-icon-bacterium" },
        { name: "nbp-icon-bahai" },
        { name: "nbp-icon-balance-scale" },
        { name: "nbp-icon-balance-scale-left" },
        { name: "nbp-icon-balance-scale-right" },
        { name: "nbp-icon-ban" },
        { name: "nbp-icon-band-aid" },
        { name: "nbp-icon-bandcamp" },
        { name: "nbp-icon-barcode" },
        { name: "nbp-icon-bars" },
        { name: "nbp-icon-baseball-ball" },
        { name: "nbp-icon-basketball-ball" },
        { name: "nbp-icon-bath" },
        { name: "nbp-icon-battery-empty" },
        { name: "nbp-icon-battery-full" },
        { name: "nbp-icon-battery-half" },
        { name: "nbp-icon-battery-quarter" },
        { name: "nbp-icon-battery-three-quarters" },
        { name: "nbp-icon-battle-net" },
        { name: "nbp-icon-bed" },
        { name: "nbp-icon-beer" },
        { name: "nbp-icon-behance" },
        { name: "nbp-icon-behance-square" },
        { name: "nbp-icon-bell" },
        { name: "nbp-icon-bell-slash" },
        { name: "nbp-icon-bezier-curve" },
        { name: "nbp-icon-bible" },
        { name: "nbp-icon-bicycle" },
        { name: "nbp-icon-biking" },
        { name: "nbp-icon-bimobject" },
        { name: "nbp-icon-binoculars" },
        { name: "nbp-icon-biohazard" },
        { name: "nbp-icon-birthday-cake" },
        { name: "nbp-icon-bitbucket" },
        { name: "nbp-icon-bitcoin" },
        { name: "nbp-icon-bity" },
        { name: "nbp-icon-black-tie" },
        { name: "nbp-icon-blackberry" },
        { name: "nbp-icon-blender" },
        { name: "nbp-icon-blender-phone" },
        { name: "nbp-icon-blind" },
        { name: "nbp-icon-blog" },
        { name: "nbp-icon-blogger" },
        { name: "nbp-icon-blogger-b" },
        { name: "nbp-icon-bluetooth" },
        { name: "nbp-icon-bluetooth-b" },
        { name: "nbp-icon-bold" },
        { name: "nbp-icon-bolt" },
        { name: "nbp-icon-bomb" },
        { name: "nbp-icon-bone" },
        { name: "nbp-icon-bong" },
        { name: "nbp-icon-book" },
        { name: "nbp-icon-book-dead" },
        { name: "nbp-icon-book-medical" },
        { name: "nbp-icon-book-open" },
        { name: "nbp-icon-book-reader" },
        { name: "nbp-icon-bookmark" },
        { name: "nbp-icon-bootstrap" },
        { name: "nbp-icon-border-all" },
        { name: "nbp-icon-border-none" },
        { name: "nbp-icon-border-style" },
        { name: "nbp-icon-bowling-ball" },
        { name: "nbp-icon-box" },
        { name: "nbp-icon-box-open" },
        { name: "nbp-icon-box-tissue" },
        { name: "nbp-icon-boxes" },
        { name: "nbp-icon-braille" },
        { name: "nbp-icon-brain" },
        { name: "nbp-icon-bread-slice" },
        { name: "nbp-icon-briefcase" },
        { name: "nbp-icon-briefcase-medical" },
        { name: "nbp-icon-broadcast-tower" },
        { name: "nbp-icon-broom" },
        { name: "nbp-icon-brush" },
        { name: "nbp-icon-btc" },
        { name: "nbp-icon-buffer" },
        { name: "nbp-icon-bug" },
        { name: "nbp-icon-building" },
        { name: "nbp-icon-bullhorn" },
        { name: "nbp-icon-bullseye" },
        { name: "nbp-icon-burn" },
        { name: "nbp-icon-buromobelexperte" },
        { name: "nbp-icon-bus" },
        { name: "nbp-icon-bus-alt" },
        { name: "nbp-icon-business-time" },
        { name: "nbp-icon-buy-n-large" },
        { name: "nbp-icon-buysellads" },
        { name: "nbp-icon-calculator" },
        { name: "nbp-icon-calendar" },
        { name: "nbp-icon-calendar-alt" },
        { name: "nbp-icon-calendar-check" },
        { name: "nbp-icon-calendar-day" },
        { name: "nbp-icon-calendar-minus" },
        { name: "nbp-icon-calendar-plus" },
        { name: "nbp-icon-calendar-times" },
        { name: "nbp-icon-calendar-week" },
        { name: "nbp-icon-camera" },
        { name: "nbp-icon-camera-retro" },
        { name: "nbp-icon-campground" },
        { name: "nbp-icon-canadian-maple-leaf" },
        { name: "nbp-icon-candy-cane" },
        { name: "nbp-icon-cannabis" },
        { name: "nbp-icon-capsules" },
        { name: "nbp-icon-car" },
        { name: "nbp-icon-car-alt" },
        { name: "nbp-icon-car-battery" },
        { name: "nbp-icon-car-crash" },
        { name: "nbp-icon-car-side" },
        { name: "nbp-icon-caravan" },
        { name: "nbp-icon-caret-down" },
        { name: "nbp-icon-caret-left" },
        { name: "nbp-icon-caret-right" },
        { name: "nbp-icon-caret-square-down" },
        { name: "nbp-icon-caret-square-left" },
        { name: "nbp-icon-caret-square-right" },
        { name: "nbp-icon-caret-square-up" },
        { name: "nbp-icon-caret-up" },
        { name: "nbp-icon-carrot" },
        { name: "nbp-icon-cart-arrow-down" },
        { name: "nbp-icon-cart-plus" },
        { name: "nbp-icon-cash-register" },
        { name: "nbp-icon-cat" },
        { name: "nbp-icon-cc-amazon-pay" },
        { name: "nbp-icon-cc-amex" },
        { name: "nbp-icon-cc-apple-pay" },
        { name: "nbp-icon-cc-diners-club" },
        { name: "nbp-icon-cc-discover" },
        { name: "nbp-icon-cc-jcb" },
        { name: "nbp-icon-cc-mastercard" },
        { name: "nbp-icon-cc-paypal" },
        { name: "nbp-icon-cc-stripe" },
        { name: "nbp-icon-cc-visa" },
        { name: "nbp-icon-centercode" },
        { name: "nbp-icon-centos" },
        ,
        { name: "nbp-icon-certificate" },
        { name: "nbp-icon-chair" },
        { name: "nbp-icon-chalkboard" },
        { name: "nbp-icon-chalkboard-teacher" },
        { name: "nbp-icon-charging-station" },
        { name: "nbp-icon-chart-area" },
        { name: "nbp-icon-chart-bar" },
        { name: "nbp-icon-chart-line" },
        { name: "nbp-icon-chart-pie" },
        { name: "nbp-icon-check" },
        { name: "nbp-icon-check-circle" },
        { name: "nbp-icon-check-double" },
        { name: "nbp-icon-check-square" },
        { name: "nbp-icon-cheese" },
        { name: "nbp-icon-chess" },
        { name: "nbp-icon-chess-bishop" },
        { name: "nbp-icon-chess-board" },
        { name: "nbp-icon-chess-king" },
        { name: "nbp-icon-chess-knight" },
        { name: "nbp-icon-chess-pawn" },
        { name: "nbp-icon-chess-queen" },
        { name: "nbp-icon-chess-rook" },
        { name: "nbp-icon-chevron-circle-down" },
        { name: "nbp-icon-chevron-circle-left" },
        { name: "nbp-icon-chevron-circle-right" },
        ,
        { name: "nbp-icon-chevron-circle-up" },
        { name: "nbp-icon-chevron-down" },
        { name: "nbp-icon-chevron-left" },
        { name: "nbp-icon-chevron-right" },
        { name: "nbp-icon-chevron-up" },
        { name: "nbp-icon-child" },
        { name: "nbp-icon-chrome" },
        { name: "nbp-icon-chromecast" },
        { name: "nbp-icon-church" },
        { name: "nbp-icon-circle" },
        { name: "nbp-icon-circle-notch" },
        { name: "nbp-icon-city" },
        { name: "nbp-icon-clinic-medical" },
        { name: "nbp-icon-clipboard" },
        { name: "nbp-icon-clipboard-check" },
        { name: "nbp-icon-clipboard-list" },
        { name: "nbp-icon-clock" },
        { name: "nbp-icon-clone" },
        { name: "nbp-icon-closed-captioning" },
        { name: "nbp-icon-cloud" },
        { name: "nbp-icon-cloud-download-alt" },
        { name: "nbp-icon-cloud-meatball" },
        { name: "nbp-icon-cloud-moon" },
        { name: "nbp-icon-cloud-moon-rain" },
        { name: "nbp-icon-cloud-rain" },
        { name: "nbp-icon-cloud-showers-heavy" },
        { name: "nbp-icon-cloud-sun" },
        { name: "nbp-icon-cloud-sun-rain" },
        { name: "nbp-icon-cloud-upload-alt" },
        { name: "nbp-icon-cloudflare" },
        { name: "nbp-icon-cloudscale" },
        { name: "nbp-icon-cloudsmith" },
        { name: "nbp-icon-cloudversify" },
        { name: "nbp-icon-cocktail" },
        { name: "nbp-icon-code" },
        { name: "nbp-icon-code-branch" },
        { name: "nbp-icon-codepen" },
        { name: "nbp-icon-codiepie" },
        { name: "nbp-icon-coffee" },
        { name: "nbp-icon-cog" },
        { name: "nbp-icon-cogs" },
        { name: "nbp-icon-coins" },
        { name: "nbp-icon-columns" },
        { name: "nbp-icon-comment" },
        { name: "nbp-icon-comment-alt" },
        { name: "nbp-icon-comment-dollar" },
        { name: "nbp-icon-comment-dots" },
        { name: "nbp-icon-comment-medical" },
        { name: "nbp-icon-comment-slash" },
        { name: "nbp-icon-comments" },
        { name: "nbp-icon-comments-dollar" },
        { name: "nbp-icon-compact-disc" },
        { name: "nbp-icon-compass" },
        { name: "nbp-icon-compress" },
        { name: "nbp-icon-compress-alt" },
        { name: "nbp-icon-compress-arrows-alt" },
        { name: "nbp-icon-concierge-bell" },
        { name: "nbp-icon-confluence" },
        { name: "nbp-icon-connectdevelop" },
        { name: "nbp-icon-contao" },
        { name: "nbp-icon-cookie" },
        { name: "nbp-icon-cookie-bite" },
        { name: "nbp-icon-copy" },
        { name: "nbp-icon-copyright" },
        { name: "nbp-icon-cotton-bureau" },
        { name: "nbp-icon-couch" },
        { name: "nbp-icon-cpanel" },
        { name: "nbp-icon-creative-commons" },
        { name: "nbp-icon-creative-commons-by" },
        { name: "nbp-icon-creative-commons-nc" },
        { name: "nbp-icon-creative-commons-nc-eu" },
        { name: "nbp-icon-creative-commons-nc-jp" },
        { name: "nbp-icon-creative-commons-nd" },
        { name: "nbp-icon-creative-commons-pd" },
        { name: "nbp-icon-creative-commons-pd-alt" },
        { name: "nbp-icon-creative-commons-remix" },
        { name: "nbp-icon-creative-commons-sa" },
        { name: "nbp-icon-creative-commons-sampling" },
        { name: "nbp-icon-creative-commons-sampling-plus" },
        { name: "nbp-icon-creative-commons-share" },
        { name: "nbp-icon-creative-commons-zero" },
        { name: "nbp-icon-credit-card" },
        { name: "nbp-icon-critical-role" },
        { name: "nbp-icon-crop" },
        { name: "nbp-icon-crop-alt" },
        { name: "nbp-icon-cross" },
        { name: "nbp-icon-crosshairs" },
        { name: "nbp-icon-crow" },
        { name: "nbp-icon-crown" },
        { name: "nbp-icon-crutch" },
        { name: "nbp-icon-css3" },
        { name: "nbp-icon-css3-alt" },
        { name: "nbp-icon-cube" },
        { name: "nbp-icon-cubes" },
        { name: "nbp-icon-cut" },
        { name: "nbp-icon-cuttlefish" },
        { name: "nbp-icon-d-and-d" },
        { name: "nbp-icon-d-and-d-beyond" },
        { name: "nbp-icon-dailymotion" },
        { name: "nbp-icon-dashcube" },
        { name: "nbp-icon-database" },
        { name: "nbp-icon-deaf" },
        { name: "nbp-icon-deezer" },
        { name: "nbp-icon-delicious" },
        { name: "nbp-icon-democrat" },
        { name: "nbp-icon-deploydog" },
        { name: "nbp-icon-deskpro" },
        { name: "nbp-icon-desktop" },
        { name: "nbp-icon-dev" },
        { name: "nbp-icon-deviantart" },
        { name: "nbp-icon-dharmachakra" },
        { name: "nbp-icon-dhl" },
        { name: "nbp-icon-diagnoses" },
        { name: "nbp-icon-diaspora" },
        { name: "nbp-icon-dice" },
        { name: "nbp-icon-dice-d" },
        { name: "nbp-icon-dice-d6" },
        { name: "nbp-icon-dice-five" },
        { name: "nbp-icon-dice-four" },
        { name: "nbp-icon-dice-one" },
        { name: "nbp-icon-dice-six" },
        { name: "nbp-icon-dice-three" },
        { name: "nbp-icon-dice-two" },
        { name: "nbp-icon-digg" },
        { name: "nbp-icon-digital-ocean" },
        { name: "nbp-icon-digital-tachograph" },
        { name: "nbp-icon-directions" },
        { name: "nbp-icon-discord" },
        { name: "nbp-icon-discourse" },
        { name: "nbp-icon-disease" },
        { name: "nbp-icon-divide" },
        { name: "nbp-icon-dizzy" },
        { name: "nbp-icon-dna" },
        { name: "nbp-icon-dochub" },
        { name: "nbp-icon-docker" },
        { name: "nbp-icon-dog" },
        { name: "nbp-icon-dollar-sign" },
        { name: "nbp-icon-dolly" },
        { name: "nbp-icon-dolly-flatbed" },
        { name: "nbp-icon-donate" },
        { name: "nbp-icon-door-closed" },
        { name: "nbp-icon-door-open" },
        { name: "nbp-icon-dot-circle" },
        { name: "nbp-icon-dove" },
        { name: "nbp-icon-download" },
        { name: "nbp-icon-draftigital" },
        { name: "nbp-icon-drafting-compass" },
        { name: "nbp-icon-dragon" },
        { name: "nbp-icon-draw-polygon" },
        { name: "nbp-icon-dribbble" },
        { name: "nbp-icon-dribbble-square" },
        { name: "nbp-icon-dropbox" },
        { name: "nbp-icon-drum" },
        { name: "nbp-icon-drum-steelpan" },
        { name: "nbp-icon-drumstick-bite" },
        { name: "nbp-icon-drupal" },
        { name: "nbp-icon-dumbbell" },
        { name: "nbp-icon-dumpster" },
        { name: "nbp-icon-dumpster-fire" },
        { name: "nbp-icon-dungeon" },
        { name: "nbp-icon-dyalog" },
        { name: "nbp-icon-earlybirds" },
        { name: "nbp-icon-ebay" },
        { name: "nbp-icon-edge" },
        { name: "nbp-icon-edge-legacy" },
        { name: "nbp-icon-edit" },
        { name: "nbp-icon-egg" },
        { name: "nbp-icon-eject" },
        { name: "nbp-icon-elementor" },
        { name: "nbp-icon-ellipsis-h" },
        { name: "nbp-icon-ellipsis-v" },
        { name: "nbp-icon-ello" },
        { name: "nbp-icon-ember" },
        { name: "nbp-icon-empire" },
        { name: "nbp-icon-envelope" },
        { name: "nbp-icon-envelope-open" },
        { name: "nbp-icon-envelope-open-text" },
        { name: "nbp-icon-envelope-square" },
        { name: "nbp-icon-envira" },
        { name: "nbp-icon-equals" },
        { name: "nbp-icon-eraser" },
        { name: "nbp-icon-erlang" },
        { name: "nbp-icon-ethereum" },
        { name: "nbp-icon-ethernet" },
        { name: "nbp-icon-etsy" },
        { name: "nbp-icon-euro-sign" },
        { name: "nbp-icon-evernote" },
        { name: "nbp-icon-exchange-alt" },
        { name: "nbp-icon-exclamation" },
        { name: "nbp-icon-exclamation-circle" },
        { name: "nbp-icon-exclamation-triangle" },
        { name: "nbp-icon-expand" },
        { name: "nbp-icon-expand-alt" },
        { name: "nbp-icon-expand-arrows-alt" },
        { name: "nbp-icon-expeditedssl" },
        { name: "nbp-icon-external-link-alt" },
        { name: "nbp-icon-external-link-square-alt" },
        { name: "nbp-icon-eye" },
        { name: "nbp-icon-eye-dropper" },
        { name: "nbp-icon-eye-slash" },
        { name: "nbp-icon-facebook" },
        { name: "nbp-icon-facebook-f" },
        { name: "nbp-icon-facebook-messenger" },
        { name: "nbp-icon-facebook-square" },
        { name: "nbp-icon-fan" },
        { name: "nbp-icon-fantasy-flight-games" },
        { name: "nbp-icon-fast-backward" },
        { name: "nbp-icon-fast-forward" },
        { name: "nbp-icon-faucet" },
        { name: "nbp-icon-fax" },
        { name: "nbp-icon-feather" },
        { name: "nbp-icon-feather-alt" },
        { name: "nbp-icon-fedex" },
        { name: "nbp-icon-fedora" },
        { name: "nbp-icon-female" },
        { name: "nbp-icon-fighter-jet" },
        { name: "nbp-icon-figma" },
        { name: "nbp-icon-file" },
        { name: "nbp-icon-file-alt" },
        { name: "nbp-icon-file-archive" },
        { name: "nbp-icon-file-audio" },
        { name: "nbp-icon-file-code" },
        { name: "nbp-icon-file-contract" },
        { name: "nbp-icon-file-csv" },
        { name: "nbp-icon-file-download" },
        { name: "nbp-icon-file-excel" },
        { name: "nbp-icon-file-export" },
        { name: "nbp-icon-file-image" },
        { name: "nbp-icon-file-import" },
        { name: "nbp-icon-file-invoice" },
        { name: "nbp-icon-file-invoice-dollar" },
        { name: "nbp-icon-file-medical" },
        { name: "nbp-icon-file-medical-alt" },
        { name: "nbp-icon-file-pdf" },
        { name: "nbp-icon-file-powerpoint" },
        { name: "nbp-icon-file-prescription" },
        { name: "nbp-icon-file-signature" },
        { name: "nbp-icon-file-upload" },
        { name: "nbp-icon-file-video" },
        { name: "nbp-icon-file-word" },
        { name: "nbp-icon-fill" },
        { name: "nbp-icon-fill-drip" },
        { name: "nbp-icon-film" },
        { name: "nbp-icon-filter" },
        { name: "nbp-icon-fingerprint" },
        { name: "nbp-icon-fire" },
        { name: "nbp-icon-fire-alt" },
        { name: "nbp-icon-fire-extinguisher" },
        { name: "nbp-icon-firefox" },
        { name: "nbp-icon-firefox-browser" },
        { name: "nbp-icon-first-aid" },
        { name: "nbp-icon-first-order" },
        { name: "nbp-icon-first-order-alt" },
        { name: "nbp-icon-firstdraft" },
        { name: "nbp-icon-fish" },
        { name: "nbp-icon-fist-raised" },
        { name: "nbp-icon-flag" },
        { name: "nbp-icon-flag-checkered" },
        { name: "nbp-icon-flag-usa" },
        { name: "nbp-icon-flask" },
        { name: "nbp-icon-flickr" },
        { name: "nbp-icon-flipboard" },
        { name: "nbp-icon-flushed" },
        { name: "nbp-icon-fly" },
        { name: "nbp-icon-folder" },
        { name: "nbp-icon-folder-minus" },
        { name: "nbp-icon-folder-open" },
        { name: "nbp-icon-folder-plus" },
        { name: "nbp-icon-font" },
        { name: "nbp-icon-font-awesome" },
        { name: "nbp-icon-font-awesome-alt" },
        { name: "nbp-icon-font-awesome-flag" },
        { name: "nbp-icon-font-awesome-logo-full" },
        { name: "nbp-icon-fonticons" },
        { name: "nbp-icon-fonticons-fi" },
        { name: "nbp-icon-football-ball" },
        { name: "nbp-icon-fort-awesome" },
        { name: "nbp-icon-fort-awesome-alt" },
        { name: "nbp-icon-forumbee" },
        { name: "nbp-icon-forward" },
        { name: "nbp-icon-foursquare" },
        { name: "nbp-icon-free-code-camp" },
        { name: "nbp-icon-freebsd" },
        { name: "nbp-icon-frog" },
        { name: "nbp-icon-frown" },
        { name: "nbp-icon-frown-open" },
        { name: "nbp-icon-fulcrum" },
        { name: "nbp-icon-funnel-dollar" },
        { name: "nbp-icon-futbol" },
        { name: "nbp-icon-galactic-republic" },
        { name: "nbp-icon-galactic-senate" },
        { name: "nbp-icon-gamepad" },
        { name: "nbp-icon-gas-pump" },
        { name: "nbp-icon-gavel" },
        { name: "nbp-icon-gem" },
        { name: "nbp-icon-genderless" },
        { name: "nbp-icon-get-pocket" },
        { name: "nbp-icon-gg" },
        { name: "nbp-icon-gg-circle" },
        { name: "nbp-icon-ghost" },
        { name: "nbp-icon-gift" },
        { name: "nbp-icon-gifts" },
        { name: "nbp-icon-git" },
        { name: "nbp-icon-git-alt" },
        { name: "nbp-icon-git-square" },
        { name: "nbp-icon-github" },
        { name: "nbp-icon-github-alt" },
        { name: "nbp-icon-github-square" },
        { name: "nbp-icon-gitkraken" },
        { name: "nbp-icon-gitlab" },
        { name: "nbp-icon-gitter" },
        { name: "nbp-icon-glass-cheers" },
        { name: "nbp-icon-glass-martini" },
        { name: "nbp-icon-glass-martini-alt" },
        { name: "nbp-icon-glass-whiskey" },
        { name: "nbp-icon-glasses" },
        { name: "nbp-icon-glide" },
        { name: "nbp-icon-glide-g" },
        { name: "nbp-icon-globe" },
        { name: "nbp-icon-globe-africa" },
        { name: "nbp-icon-globe-americas" },
        { name: "nbp-icon-globe-asia" },
        { name: "nbp-icon-globe-europe" },
        { name: "nbp-icon-gofore" },
        { name: "nbp-icon-golf-ball" },
        { name: "nbp-icon-goodreads" },
        { name: "nbp-icon-goodreads-g" },
        { name: "nbp-icon-google" },
        { name: "nbp-icon-google-drive" },
        { name: "nbp-icon-google-pay" },
        { name: "nbp-icon-google-play" },
        { name: "nbp-icon-google-plus" },
        { name: "nbp-icon-google-plus-g" },
        { name: "nbp-icon-google-plus-square" },
        { name: "nbp-icon-google-wallet" },
        { name: "nbp-icon-gopuram" },
        { name: "nbp-icon-graduation-cap" },
        { name: "nbp-icon-gratipay" },
        { name: "nbp-icon-grav" },
        { name: "nbp-icon-greater-than" },
        { name: "nbp-icon-greater-than-equal" },
        { name: "nbp-icon-grimace" },
        { name: "nbp-icon-grin" },
        { name: "nbp-icon-grin-alt" },
        { name: "nbp-icon-grin-beam" },
        { name: "nbp-icon-grin-beam-sweat" },
        { name: "nbp-icon-grin-hearts" },
        { name: "nbp-icon-grin-squint" },
        { name: "nbp-icon-grin-squint-tears" },
        { name: "nbp-icon-grin-stars" },
        { name: "nbp-icon-grin-tears" },
        { name: "nbp-icon-grin-tongue" },
        { name: "nbp-icon-grin-tongue-squint" },
        { name: "nbp-icon-grin-tongue-wink" },
        { name: "nbp-icon-grin-wink" },
        { name: "nbp-icon-grip-horizontal" },
        { name: "nbp-icon-grip-lines" },
        { name: "nbp-icon-grip-lines-vertical" },
        { name: "nbp-icon-grip-vertical" },
        { name: "nbp-icon-gripfire" },
        { name: "nbp-icon-grunt" },
        { name: "nbp-icon-guilded" },
        { name: "nbp-icon-guitar" },
        { name: "nbp-icon-gulp" },
        { name: "nbp-icon-h-square" },
        { name: "nbp-icon-hacker-news" },
        { name: "nbp-icon-hacker-news-square" },
        { name: "nbp-icon-hackerrank" },
        { name: "nbp-icon-hamburger" },
        { name: "nbp-icon-hammer" },
        { name: "nbp-icon-hamsa" },
        { name: "nbp-icon-hand-holding" },
        { name: "nbp-icon-hand-holding-heart" },
        { name: "nbp-icon-hand-holding-medical" },
        { name: "nbp-icon-hand-holding-usd" },
        { name: "nbp-icon-hand-holding-water" },
        { name: "nbp-icon-hand-lizard" },
        { name: "nbp-icon-hand-middle-finger" },
        { name: "nbp-icon-hand-paper" },
        { name: "nbp-icon-hand-peace" },
        { name: "nbp-icon-hand-point-down" },
        { name: "nbp-icon-hand-point-left" },
        { name: "nbp-icon-hand-point-right" },
        { name: "nbp-icon-hand-point-up" },
        { name: "nbp-icon-hand-pointer" },
        { name: "nbp-icon-hand-rock" },
        { name: "nbp-icon-hand-scissors" },
        { name: "nbp-icon-hand-sparkles" },
        { name: "nbp-icon-hand-spock" },
        { name: "nbp-icon-hands" },
        { name: "nbp-icon-hands-helping" },
        { name: "nbp-icon-hands-wash" },
        { name: "nbp-icon-handshake" },
        { name: "nbp-icon-handshake-alt-slash" },
        { name: "nbp-icon-handshake-slash" },
        { name: "nbp-icon-hanukiah" },
        { name: "nbp-icon-hard-hat" },
        { name: "nbp-icon-hashtag" },
        { name: "nbp-icon-hat-cowboy" },
        { name: "nbp-icon-hat-cowboy-side" },
        { name: "nbp-icon-hat-wizard" },
        { name: "nbp-icon-hdd" },
        { name: "nbp-icon-head-side-cough" },
        { name: "nbp-icon-head-side-cough-slash" },
        { name: "nbp-icon-head-side-mask" },
        { name: "nbp-icon-head-side-virus" },
        { name: "nbp-icon-heading" },
        { name: "nbp-icon-headphones" },
        { name: "nbp-icon-headphones-alt" },
        { name: "nbp-icon-headset" },
        { name: "nbp-icon-heart" },
        { name: "nbp-icon-heart-broken" },
        { name: "nbp-icon-heartbeat" },
        { name: "nbp-icon-helicopter" },
        { name: "nbp-icon-highlighter" },
        { name: "nbp-icon-hiking" },
        { name: "nbp-icon-hippo" },
        { name: "nbp-icon-hips" },
        { name: "nbp-icon-hire-a-helper" },
        { name: "nbp-icon-history" },
        { name: "nbp-icon-hive" },
        { name: "nbp-icon-hockey-puck" },
        { name: "nbp-icon-holly-berry" },
        { name: "nbp-icon-home" },
        { name: "nbp-icon-hooli" },
        { name: "nbp-icon-hornbill" },
        { name: "nbp-icon-horse" },
        { name: "nbp-icon-horse-head" },
        { name: "nbp-icon-hospital" },
        { name: "nbp-icon-hospital-alt" },
        { name: "nbp-icon-hospital-symbol" },
        { name: "nbp-icon-hospital-user" },
        { name: "nbp-icon-hot-tub" },
        { name: "nbp-icon-hotdog" },
        { name: "nbp-icon-hotel" },
        { name: "nbp-icon-hotjar" },
        { name: "nbp-icon-hourglass" },
        { name: "nbp-icon-hourglass-end" },
        { name: "nbp-icon-hourglass-half" },
        { name: "nbp-icon-hourglass-start" },
        { name: "nbp-icon-house-damage" },
        { name: "nbp-icon-house-user" },
        { name: "nbp-icon-houzz" },
        { name: "nbp-icon-hryvnia" },
        { name: "nbp-icon-html5" },
        { name: "nbp-icon-hubspot" },
        { name: "nbp-icon-i-cursor" },
        { name: "nbp-icon-ice-cream" },
        { name: "nbp-icon-icicles" },
        { name: "nbp-icon-icons" },
        { name: "nbp-icon-id-badge" },
        { name: "nbp-icon-id-card" },
        { name: "nbp-icon-id-card-alt" },
        { name: "nbp-icon-ideal" },
        { name: "nbp-icon-igloo" },
        { name: "nbp-icon-image" },
        { name: "nbp-icon-images" },
        { name: "nbp-icon-imdb" },
        { name: "nbp-icon-inbox" },
        { name: "nbp-icon-indent" },
        { name: "nbp-icon-industry" },
        { name: "nbp-icon-infinity" },
        { name: "nbp-icon-info" },
        { name: "nbp-icon-info-circle" },
        { name: "nbp-icon-innosoft" },
        { name: "nbp-icon-instagram" },
        { name: "nbp-icon-instagram-square" },
        { name: "nbp-icon-instalod" },
        { name: "nbp-icon-intercom" },
        { name: "nbp-icon-internet-explorer" },
        { name: "nbp-icon-invision" },
        { name: "nbp-icon-ioxhost" },
        { name: "nbp-icon-italic" },
        { name: "nbp-icon-itch-io" },
        { name: "nbp-icon-itunes" },
        { name: "nbp-icon-itunes-note" },
        { name: "nbp-icon-java" },
        { name: "nbp-icon-jedi" },
        { name: "nbp-icon-jedi-order" },
        { name: "nbp-icon-jenkins" },
        { name: "nbp-icon-jira" },
        { name: "nbp-icon-joget" },
        { name: "nbp-icon-joint" },
        { name: "nbp-icon-joomla" },
        { name: "nbp-icon-journal-whills" },
        { name: "nbp-icon-js" },
        { name: "nbp-icon-js-square" },
        { name: "nbp-icon-jsfiddle" },
        { name: "nbp-icon-kaaba" },
        { name: "nbp-icon-kaggle" },
        { name: "nbp-icon-key" },
        { name: "nbp-icon-keybase" },
        { name: "nbp-icon-keyboard" },
        { name: "nbp-icon-keycdn" },
        { name: "nbp-icon-khanda" },
        { name: "nbp-icon-kickstarter" },
        { name: "nbp-icon-kickstarter-k" },
        { name: "nbp-icon-kiss" },
        { name: "nbp-icon-kiss-beam" },
        { name: "nbp-icon-kiss-wink-heart" },
        { name: "nbp-icon-kiwi-bird" },
        { name: "nbp-icon-korvue" },
        { name: "nbp-icon-landmark" },
        { name: "nbp-icon-language" },
        { name: "nbp-icon-laptop" },
        { name: "nbp-icon-laptop-code" },
        { name: "nbp-icon-laptop-house" },
        { name: "nbp-icon-laptop-medical" },
        { name: "nbp-icon-laravel" },
        { name: "nbp-icon-lastfm" },
        { name: "nbp-icon-lastfm-square" },
        { name: "nbp-icon-laugh" },
        { name: "nbp-icon-laugh-beam" },
        { name: "nbp-icon-laugh-squint" },
        { name: "nbp-icon-laugh-wink" },
        { name: "nbp-icon-layer-group" },
        { name: "nbp-icon-leaf" },
        { name: "nbp-icon-leanpub" },
        { name: "nbp-icon-lemon" },
        { name: "nbp-icon-less" },
        { name: "nbp-icon-less-than" },
        { name: "nbp-icon-less-than-equal" },
        { name: "nbp-icon-level-down-alt" },
        { name: "nbp-icon-level-up-alt" },
        { name: "nbp-icon-life-ring" },
        { name: "nbp-icon-lightbulb" },
        { name: "nbp-icon-line" },
        { name: "nbp-icon-link" },
        { name: "nbp-icon-linkedin" },
        { name: "nbp-icon-linkedin-in" },
        { name: "nbp-icon-linode" },
        { name: "nbp-icon-linux" },
        { name: "nbp-icon-lira-sign" },
        { name: "nbp-icon-list" },
        { name: "nbp-icon-list-alt" },
        { name: "nbp-icon-list-ol" },
        { name: "nbp-icon-list-ul" },
        { name: "nbp-icon-location-arrow" },
        { name: "nbp-icon-lock" },
        { name: "nbp-icon-lock-open" },
        { name: "nbp-icon-long-arrow-alt-down" },
        { name: "nbp-icon-long-arrow-alt-left" },
        { name: "nbp-icon-long-arrow-alt-right" },
        { name: "nbp-icon-long-arrow-alt-up" },
        { name: "nbp-icon-low-vision" },
        { name: "nbp-icon-luggage-cart" },
        { name: "nbp-icon-lungs" },
        { name: "nbp-icon-lungs-virus" },
        { name: "nbp-icon-lyft" },
        { name: "nbp-icon-magento" },
        { name: "nbp-icon-magic" },
        { name: "nbp-icon-magnet" },
        { name: "nbp-icon-mail-bulk" },
        { name: "nbp-icon-mailchimp" },
        { name: "nbp-icon-male" },
        { name: "nbp-icon-mandalorian" },
        { name: "nbp-icon-map" },
        { name: "nbp-icon-map-marked" },
        { name: "nbp-icon-map-marked-alt" },
        { name: "nbp-icon-map-marker" },
        { name: "nbp-icon-map-marker-alt" },
        { name: "nbp-icon-map-pin" },
        { name: "nbp-icon-map-signs" },
        { name: "nbp-icon-markdown" },
        { name: "nbp-icon-marker" },
        { name: "nbp-icon-mars" },
        { name: "nbp-icon-mars-double" },
        { name: "nbp-icon-mars-stroke" },
        { name: "nbp-icon-mars-stroke-h" },
        { name: "nbp-icon-mars-stroke-v" },
        { name: "nbp-icon-mask" },
        { name: "nbp-icon-mastodon" },
        { name: "nbp-icon-maxcdn" },
        { name: "nbp-icon-mdb" },
        { name: "nbp-icon-medal" },
        { name: "nbp-icon-medapps" },
        { name: "nbp-icon-medium" },
        { name: "nbp-icon-medium-m" },
        { name: "nbp-icon-medkit" },
        { name: "nbp-icon-medrt" },
        { name: "nbp-icon-meetup" },
        { name: "nbp-icon-megaport" },
        { name: "nbp-icon-meh" },
        { name: "nbp-icon-meh-blank" },
        { name: "nbp-icon-meh-rolling-eyes" },
        { name: "nbp-icon-memory" },
        { name: "nbp-icon-mendeley" },
        { name: "nbp-icon-menorah" },
        { name: "nbp-icon-mercury" },
        { name: "nbp-icon-meteor" },
        { name: "nbp-icon-microblog" },
        { name: "nbp-icon-microchip" },
        { name: "nbp-icon-microphone" },
        { name: "nbp-icon-microphone-alt" },
        { name: "nbp-icon-microphone-alt-slash" },
        { name: "nbp-icon-microphone-slash" },
        { name: "nbp-icon-microscope" },
        { name: "nbp-icon-microsoft" },
        { name: "nbp-icon-minus" },
        { name: "nbp-icon-minus-circle" },
        { name: "nbp-icon-minus-square" },
        { name: "nbp-icon-mitten" },
        { name: "nbp-icon-mix" },
        { name: "nbp-icon-mixcloud" },
        { name: "nbp-icon-mixer" },
        { name: "nbp-icon-mizuni" },
        { name: "nbp-icon-mobile" },
        { name: "nbp-icon-mobile-alt" },
        { name: "nbp-icon-modx" },
        { name: "nbp-icon-monero" },
        { name: "nbp-icon-money-bill" },
        { name: "nbp-icon-money-bill-alt" },
        { name: "nbp-icon-money-bill-wave" },
        { name: "nbp-icon-money-bill-wave-alt" },
        { name: "nbp-icon-money-check" },
        { name: "nbp-icon-money-check-alt" },
        { name: "nbp-icon-monument" },
        { name: "nbp-icon-moon" },
        { name: "nbp-icon-mortar-pestle" },
        { name: "nbp-icon-mosque" },
        { name: "nbp-icon-motorcycle" },
        { name: "nbp-icon-mountain" },
        { name: "nbp-icon-mouse" },
        { name: "nbp-icon-mouse-pointer" },
        { name: "nbp-icon-mug-hot" },
        { name: "nbp-icon-music" },
        { name: "nbp-icon-napster" },
        { name: "nbp-icon-neos" },
        { name: "nbp-icon-network-wired" },
        { name: "nbp-icon-neuter" },
        { name: "nbp-icon-newspaper" },
        { name: "nbp-icon-nimblr" },
        { name: "nbp-icon-node" },
        { name: "nbp-icon-node-js" },
        { name: "nbp-icon-not-equal" },
        { name: "nbp-icon-notes-medical" },
        { name: "nbp-icon-npm" },
        { name: "nbp-icon-ns8" },
        { name: "nbp-icon-nutritionix" },
        { name: "nbp-icon-object-group" },
        { name: "nbp-icon-object-ungroup" },
        { name: "nbp-icon-octopus-deploy" },
        { name: "nbp-icon-odnoklassniki" },
        { name: "nbp-icon-odnoklassniki-square" },
        { name: "nbp-icon-oil-can" },
        { name: "nbp-icon-old-republic" },
        { name: "nbp-icon-om" },
        { name: "nbp-icon-opencart" },
        { name: "nbp-icon-openid" },
        { name: "nbp-icon-opera" },
        { name: "nbp-icon-optin-monster" },
        { name: "nbp-icon-orcid" },
        { name: "nbp-icon-osi" },
        { name: "nbp-icon-otter" },
        { name: "nbp-icon-outdent" },
        { name: "nbp-icon-page4" },
        { name: "nbp-icon-pagelines" },
        { name: "nbp-icon-pager" },
        { name: "nbp-icon-paint-brush" },
        { name: "nbp-icon-paint-roller" },
        { name: "nbp-icon-palette" },
        { name: "nbp-icon-palfed" },
        { name: "nbp-icon-pallet" },
        { name: "nbp-icon-paper-plane" },
        { name: "nbp-icon-paperclip" },
        { name: "nbp-icon-parachute-box" },
        { name: "nbp-icon-paragraph" },
        { name: "nbp-icon-parking" },
        { name: "nbp-icon-passport" },
        { name: "nbp-icon-pastafarianism" },
        { name: "nbp-icon-paste" },
        { name: "nbp-icon-patreon" },
        { name: "nbp-icon-pause" },
        { name: "nbp-icon-pause-circle" },
        { name: "nbp-icon-paw" },
        { name: "nbp-icon-paypal" },
        { name: "nbp-icon-peace" },
        { name: "nbp-icon-pen" },
        { name: "nbp-icon-pen-alt" },
        { name: "nbp-icon-pen-fancy" },
        { name: "nbp-icon-pen-nib" },
        { name: "nbp-icon-pen-square" },
        { name: "nbp-icon-pencil-alt" },
        { name: "nbp-icon-pencil-ruler" },
        { name: "nbp-icon-penny-arcade" },
        { name: "nbp-icon-people-arrows" },
        { name: "nbp-icon-people-carry" },
        { name: "nbp-icon-pepper-hot" },
        { name: "nbp-icon-perbyte" },
        { name: "nbp-icon-percent" },
        { name: "nbp-icon-percentage" },
        { name: "nbp-icon-periscope" },
        { name: "nbp-icon-person-booth" },
        { name: "nbp-icon-phabricator" },
        { name: "nbp-icon-phoenix-framework" },
        { name: "nbp-icon-phoenix-squadron" },
        { name: "nbp-icon-phone" },
        { name: "nbp-icon-phone-alt" },
        { name: "nbp-icon-phone-slash" },
        { name: "nbp-icon-phone-square" },
        { name: "nbp-icon-phone-square-alt" },
        { name: "nbp-icon-phone-volume" },
        { name: "nbp-icon-photo-video" },
        { name: "nbp-icon-php" },
        { name: "nbp-icon-pied-piper" },
        { name: "nbp-icon-pied-piper-alt" },
        { name: "nbp-icon-pied-piper-hat" },
        { name: "nbp-icon-pied-piper-pp" },
        { name: "nbp-icon-pied-piper-square" },
        { name: "nbp-icon-piggy-bank" },
        { name: "nbp-icon-pills" },
        { name: "nbp-icon-pinterest" },
        { name: "nbp-icon-pinterest-p" },
        { name: "nbp-icon-pinterest-square" },
        { name: "nbp-icon-pizza-slice" },
        { name: "nbp-icon-place-of-worship" },
        { name: "nbp-icon-plane" },
        { name: "nbp-icon-plane-arrival" },
        { name: "nbp-icon-plane-departure" },
        { name: "nbp-icon-plane-slash" },
        { name: "nbp-icon-play" },
        { name: "nbp-icon-play-circle" },
        { name: "nbp-icon-playstation" },
        { name: "nbp-icon-plug" },
        { name: "nbp-icon-plus" },
        { name: "nbp-icon-plus-circle" },
        { name: "nbp-icon-plus-square" },
        { name: "nbp-icon-podcast" },
        { name: "nbp-icon-poll" },
        { name: "nbp-icon-poll-h" },
        { name: "nbp-icon-poo" },
        { name: "nbp-icon-poo-storm" },
        { name: "nbp-icon-poop" },
        { name: "nbp-icon-portrait" },
        { name: "nbp-icon-pound-sign" },
        { name: "nbp-icon-power-off" },
        { name: "nbp-icon-pray" },
        { name: "nbp-icon-praying-hands" },
        { name: "nbp-icon-prescription" },
        { name: "nbp-icon-prescription-bottle" },
        { name: "nbp-icon-prescription-bottle-alt" },
        { name: "nbp-icon-print" },
        { name: "nbp-icon-procedures" },
        { name: "nbp-icon-product-hunt" },
        { name: "nbp-icon-project-diagram" },
        { name: "nbp-icon-pump-medical" },
        { name: "nbp-icon-pump-soap" },
        { name: "nbp-icon-pushed" },
        { name: "nbp-icon-puzzle-piece" },
        { name: "nbp-icon-python" },
        { name: "nbp-icon-qq" },
        { name: "nbp-icon-qrcode" },
        { name: "nbp-icon-question" },
        { name: "nbp-icon-question-circle" },
        { name: "nbp-icon-quidditch" },
        { name: "nbp-icon-quinscape" },
        { name: "nbp-icon-quora" },
        { name: "nbp-icon-quote-left" },
        { name: "nbp-icon-quote-right" },
        { name: "nbp-icon-quran" },
        { name: "nbp-icon-r-project" },
        { name: "nbp-icon-radiation" },
        { name: "nbp-icon-radiation-alt" },
        { name: "nbp-icon-rainbow" },
        { name: "nbp-icon-random" },
        { name: "nbp-icon-raspberry-pi" },
        { name: "nbp-icon-ravelry" },
        { name: "nbp-icon-react" },
        { name: "nbp-icon-reacteurope" },
        { name: "nbp-icon-readme" },
        { name: "nbp-icon-rebel" },
        { name: "nbp-icon-receipt" },
        { name: "nbp-icon-record-vinyl" },
        { name: "nbp-icon-recycle" },
        { name: "nbp-icon-red-river" },
        { name: "nbp-icon-reddit" },
        { name: "nbp-icon-reddit-alien" },
        { name: "nbp-icon-reddit-square" },
        { name: "nbp-icon-redhat" },
        { name: "nbp-icon-redo" },
        { name: "nbp-icon-redo-alt" },
        { name: "nbp-icon-registered" },
        { name: "nbp-icon-remove-format" },
        { name: "nbp-icon-renren" },
        { name: "nbp-icon-reply" },
        { name: "nbp-icon-reply-all" },
        { name: "nbp-icon-replyd" },
        { name: "nbp-icon-republican" },
        { name: "nbp-icon-researchgate" },
        { name: "nbp-icon-resolving" },
        { name: "nbp-icon-restroom" },
        { name: "nbp-icon-retweet" },
        { name: "nbp-icon-rev" },
        { name: "nbp-icon-ribbon" },
        { name: "nbp-icon-ring" },
        { name: "nbp-icon-road" },
        { name: "nbp-icon-robot" },
        { name: "nbp-icon-rocket" },
        { name: "nbp-icon-rocketchat" },
        { name: "nbp-icon-rockrms" },
        { name: "nbp-icon-route" },
        { name: "nbp-icon-rss" },
        { name: "nbp-icon-rss-square" },
        { name: "nbp-icon-ruble-sign" },
        { name: "nbp-icon-ruler" },
        { name: "nbp-icon-ruler-combined" },
        { name: "nbp-icon-ruler-horizontal" },
        { name: "nbp-icon-ruler-vertical" },
        { name: "nbp-icon-running" },
        { name: "nbp-icon-rupee-sign" },
        { name: "nbp-icon-rust" },
        { name: "nbp-icon-sad-cry" },
        { name: "nbp-icon-sad-tear" },
        { name: "nbp-icon-safari" },
        { name: "nbp-icon-salesforce" },
        { name: "nbp-icon-sass" },
        { name: "nbp-icon-satellite" },
        { name: "nbp-icon-satellite-dish" },
        { name: "nbp-icon-save" },
        { name: "nbp-icon-schlix" },
        { name: "nbp-icon-school" },
        { name: "nbp-icon-screwdriver" },
        { name: "nbp-icon-scribd" },
        { name: "nbp-icon-scroll" },
        { name: "nbp-icon-sd-card" },
        { name: "nbp-icon-search" },
        { name: "nbp-icon-search-dollar" },
        { name: "nbp-icon-search-location" },
        { name: "nbp-icon-search-minus" },
        { name: "nbp-icon-search-plus" },
        { name: "nbp-icon-searchengin" },
        { name: "nbp-icon-seedling" },
        { name: "nbp-icon-sellcast" },
        { name: "nbp-icon-sellsy" },
        { name: "nbp-icon-server" },
        { name: "nbp-icon-servicestack" },
        { name: "nbp-icon-shapes" },
        { name: "nbp-icon-share" },
        { name: "nbp-icon-share-alt" },
        { name: "nbp-icon-share-alt-square" },
        { name: "nbp-icon-share-square" },
        { name: "nbp-icon-shekel-sign" },
        { name: "nbp-icon-shield-alt" },
        { name: "nbp-icon-shield-virus" },
        { name: "nbp-icon-ship" },
        { name: "nbp-icon-shipping-fast" },
        { name: "nbp-icon-shirtsinbulk" },
        { name: "nbp-icon-shoe-prints" },
        { name: "nbp-icon-shopify" },
        { name: "nbp-icon-shopping-bag" },
        { name: "nbp-icon-shopping-basket" },
        { name: "nbp-icon-shopping-cart" },
        { name: "nbp-icon-shopware" },
        { name: "nbp-icon-shower" },
        { name: "nbp-icon-shuttle-van" },
        { name: "nbp-icon-sign" },
        { name: "nbp-icon-sign-in-alt" },
        { name: "nbp-icon-sign-language" },
        { name: "nbp-icon-sign-out-alt" },
        { name: "nbp-icon-signal" },
        { name: "nbp-icon-signature" },
        { name: "nbp-icon-sim-card" },
        { name: "nbp-icon-simplybuilt" },
        { name: "nbp-icon-sink" },
        { name: "nbp-icon-sistrix" },
        { name: "nbp-icon-sitemap" },
        { name: "nbp-icon-sith" },
        { name: "nbp-icon-skating" },
        { name: "nbp-icon-sketch" },
        { name: "nbp-icon-skiing" },
        { name: "nbp-icon-skiing-nordic" },
        { name: "nbp-icon-skull" },
        { name: "nbp-icon-skull-crossbones" },
        { name: "nbp-icon-skyatlas" },
        { name: "nbp-icon-skype" },
        { name: "nbp-icon-slack" },
        { name: "nbp-icon-slack-hash" },
        { name: "nbp-icon-slash" },
        { name: "nbp-icon-sleigh" },
        { name: "nbp-icon-sliders-h" },
        { name: "nbp-icon-slideshare" },
        { name: "nbp-icon-smile" },
        { name: "nbp-icon-smile-beam" },
        { name: "nbp-icon-smile-wink" },
        { name: "nbp-icon-smog" },
        { name: "nbp-icon-smoking" },
        { name: "nbp-icon-smoking-ban" },
        { name: "nbp-icon-sms" },
        { name: "nbp-icon-snapchat" },
        { name: "nbp-icon-snapchat-ghost" },
        { name: "nbp-icon-snapchat-square" },
        { name: "nbp-icon-snowboarding" },
        { name: "nbp-icon-snowflake" },
        { name: "nbp-icon-snowman" },
        { name: "nbp-icon-snowplow" },
        { name: "nbp-icon-soap" },
        { name: "nbp-icon-socks" },
        { name: "nbp-icon-solar-panel" },
        { name: "nbp-icon-sort" },
        { name: "nbp-icon-sort-alpha-down" },
        { name: "nbp-icon-sort-alpha-down-alt" },
        { name: "nbp-icon-sort-alpha-up" },
        { name: "nbp-icon-sort-alpha-up-alt" },
        { name: "nbp-icon-sort-amount-down" },
        { name: "nbp-icon-sort-amount-down-alt" },
        { name: "nbp-icon-sort-amount-up" },
        { name: "nbp-icon-sort-amount-up-alt" },
        { name: "nbp-icon-sort-down" },
        { name: "nbp-icon-sort-numeric-down" },
        { name: "nbp-icon-sort-numeric-down-alt" },
        { name: "nbp-icon-sort-numeric-up" },
        { name: "nbp-icon-sort-numeric-up-alt" },
        { name: "nbp-icon-sort-up" },
        { name: "nbp-icon-soundcloud" },
        { name: "nbp-icon-sourcetree" },
        { name: "nbp-icon-spa" },
        { name: "nbp-icon-space-shuttle" },
        { name: "nbp-icon-speakap" },
        { name: "nbp-icon-speaker-deck" },
        { name: "nbp-icon-spell-check" },
        { name: "nbp-icon-spider" },
        { name: "nbp-icon-spinner" },
        { name: "nbp-icon-splotch" },
        { name: "nbp-icon-spotify" },
        { name: "nbp-icon-spray-can" },
        { name: "nbp-icon-square" },
        { name: "nbp-icon-square-full" },
        { name: "nbp-icon-square-root-alt" },
        { name: "nbp-icon-squarespace" },
        { name: "nbp-icon-stack-exchange" },
        { name: "nbp-icon-stack-overflow" },
        { name: "nbp-icon-stackpath" },
        { name: "nbp-icon-stamp" },
        { name: "nbp-icon-star" },
        { name: "nbp-icon-star-and-crescent" },
        { name: "nbp-icon-star-half" },
        { name: "nbp-icon-star-half-alt" },
        { name: "nbp-icon-star-of-david" },
        { name: "nbp-icon-star-of-life" },
        { name: "nbp-icon-staylinked" },
        { name: "nbp-icon-steam" },
        { name: "nbp-icon-steam-square" },
        { name: "nbp-icon-steam-symbol" },
        { name: "nbp-icon-step-backward" },
        { name: "nbp-icon-step-forward" },
        { name: "nbp-icon-stethoscope" },
        { name: "nbp-icon-sticker-mule" },
        { name: "nbp-icon-sticky-note" },
        { name: "nbp-icon-stop" },
        { name: "nbp-icon-stop-circle" },
        { name: "nbp-icon-stopwatch" },
        { name: "nbp-icon-stopwatch-20" },
        { name: "nbp-icon-store" },
        { name: "nbp-icon-store-alt" },
        { name: "nbp-icon-store-alt-slash" },
        { name: "nbp-icon-store-slash" },
        { name: "nbp-icon-strava" },
        { name: "nbp-icon-stream" },
        { name: "nbp-icon-street-view" },
        { name: "nbp-icon-strikethrough" },
        { name: "nbp-icon-stripe" },
        { name: "nbp-icon-stripe-s" },
        { name: "nbp-icon-stroopwafel" },
        { name: "nbp-icon-studiovinari" },
        { name: "nbp-icon-stumbleupon" },
        { name: "nbp-icon-stumbleupon-circle" },
        { name: "nbp-icon-subscript" },
        { name: "nbp-icon-subway" },
        { name: "nbp-icon-suitcase" },
        { name: "nbp-icon-suitcase-rolling" },
        { name: "nbp-icon-sun" },
        { name: "nbp-icon-superpowers" },
        { name: "nbp-icon-superscript" },
        { name: "nbp-icon-supple" },
        { name: "nbp-icon-surprise" },
        { name: "nbp-icon-suse" },
        { name: "nbp-icon-swatchbook" },
        { name: "nbp-icon-swift" },
        { name: "nbp-icon-swimmer" },
        { name: "nbp-icon-swimming-pool" },
        { name: "nbp-icon-symfony" },
        { name: "nbp-icon-synagogue" },
        { name: "nbp-icon-sync" },
        { name: "nbp-icon-sync-alt" },
        { name: "nbp-icon-syringe" },
        { name: "nbp-icon-table" },
        { name: "nbp-icon-table-tennis" },
        { name: "nbp-icon-tablet" },
        { name: "nbp-icon-tablet-alt" },
        { name: "nbp-icon-tablets" },
        { name: "nbp-icon-tachometer-alt" },
        { name: "nbp-icon-tag" },
        { name: "nbp-icon-tags" },
        { name: "nbp-icon-tape" },
        { name: "nbp-icon-tasks" },
        { name: "nbp-icon-taxi" },
        { name: "nbp-icon-teamspeak" },
        { name: "nbp-icon-teeth" },
        { name: "nbp-icon-teeth-open" },
        { name: "nbp-icon-telegram" },
        { name: "nbp-icon-telegram-plane" },
        { name: "nbp-icon-temperature-high" },
        { name: "nbp-icon-temperature-low" },
        { name: "nbp-icon-tencent-weibo" },
        { name: "nbp-icon-tenge" },
        { name: "nbp-icon-terminal" },
        { name: "nbp-icon-text-height" },
        { name: "nbp-icon-text-width" },
        { name: "nbp-icon-th" },
        { name: "nbp-icon-th-large" },
        { name: "nbp-icon-th-list" },
        { name: "nbp-icon-the-red-yeti" },
        { name: "nbp-icon-theater-masks" },
        { name: "nbp-icon-themeco" },
        { name: "nbp-icon-themeisle" },
        { name: "nbp-icon-thermometer" },
        { name: "nbp-icon-thermometer-empty" },
        { name: "nbp-icon-thermometer-full" },
        { name: "nbp-icon-thermometer-half" },
        { name: "nbp-icon-thermometer-quarter" },
        { name: "nbp-icon-thermometer-three-quarters" },
        { name: "nbp-icon-think-peaks" },
        { name: "nbp-icon-thumbs-down" },
        { name: "nbp-icon-thumbs-up" },
        { name: "nbp-icon-thumbtack" },
        { name: "nbp-icon-ticket-alt" },
        { name: "nbp-icon-tiktok" },
        { name: "nbp-icon-times" },
        { name: "nbp-icon-times-circle" },
        { name: "nbp-icon-tint" },
        { name: "nbp-icon-tint-slash" },
        { name: "nbp-icon-tired" },
        { name: "nbp-icon-toggle-off" },
        { name: "nbp-icon-toggle-on" },
        { name: "nbp-icon-toilet" },
        { name: "nbp-icon-toilet-paper" },
        { name: "nbp-icon-toilet-paper-slash" },
        { name: "nbp-icon-toolbox" },
        { name: "nbp-icon-tools" },
        { name: "nbp-icon-tooth" },
        { name: "nbp-icon-torah" },
        { name: "nbp-icon-torii-gate" },
        { name: "nbp-icon-tractor" },
        { name: "nbp-icon-trade-federation" },
        { name: "nbp-icon-trademark" },
        { name: "nbp-icon-traffic-light" },
        { name: "nbp-icon-trailer" },
        { name: "nbp-icon-train" },
        { name: "nbp-icon-tram" },
        { name: "nbp-icon-transgender" },
        { name: "nbp-icon-transgender-alt" },
        { name: "nbp-icon-trash" },
        { name: "nbp-icon-trash-alt" },
        { name: "nbp-icon-trash-restore" },
        { name: "nbp-icon-trash-restore-alt" },
        { name: "nbp-icon-tree" },
        { name: "nbp-icon-trello" },
        { name: "nbp-icon-tripadvisor" },
        { name: "nbp-icon-trophy" },
        { name: "nbp-icon-truck" },
        { name: "nbp-icon-truck-loading" },
        { name: "nbp-icon-truck-monster" },
        { name: "nbp-icon-truck-moving" },
        { name: "nbp-icon-truck-pickup" },
        { name: "nbp-icon-tshirt" },
        { name: "nbp-icon-tty" },
        { name: "nbp-icon-tumblr" },
        { name: "nbp-icon-tumblr-square" },
        { name: "nbp-icon-tv" },
        { name: "nbp-icon-twitch" },
        { name: "nbp-icon-twitter" },
        { name: "nbp-icon-twitter-square" },
        { name: "nbp-icon-typo3" },
        { name: "nbp-icon-uber" },
        { name: "nbp-icon-ubuntu" },
        { name: "nbp-icon-uikit" },
        { name: "nbp-icon-umbraco" },
        { name: "nbp-icon-umbrella" },
        { name: "nbp-icon-umbrella-beach" },
        { name: "nbp-icon-uncharted" },
        { name: "nbp-icon-underline" },
        { name: "nbp-icon-undo" },
        { name: "nbp-icon-undo-alt" },
        { name: "nbp-icon-uniregistry" },
        { name: "nbp-icon-unity" },
        { name: "nbp-icon-universal-access" },
        { name: "nbp-icon-university" },
        { name: "nbp-icon-unlink" },
        { name: "nbp-icon-unlock" },
        { name: "nbp-icon-unlock-alt" },
        { name: "nbp-icon-unsplash" },
        { name: "nbp-icon-untappd" },
        { name: "nbp-icon-upload" },
        { name: "nbp-icon-ups" },
        { name: "nbp-icon-usb" },
        { name: "nbp-icon-user" },
        { name: "nbp-icon-user-alt" },
        { name: "nbp-icon-user-alt-slash" },
        { name: "nbp-icon-user-astronaut" },
        { name: "nbp-icon-user-check" },
        { name: "nbp-icon-user-circle" },
        { name: "nbp-icon-user-clock" },
        { name: "nbp-icon-user-cog" },
        { name: "nbp-icon-user-edit" },
        { name: "nbp-icon-user-friends" },
        { name: "nbp-icon-user-graduate" },
        { name: "nbp-icon-user-injured" },
        { name: "nbp-icon-user-lock" },
        { name: "nbp-icon-user-md" },
        { name: "nbp-icon-user-minus" },
        { name: "nbp-icon-user-ninja" },
        { name: "nbp-icon-user-nurse" },
        { name: "nbp-icon-user-plus" },
        { name: "nbp-icon-user-secret" },
        { name: "nbp-icon-user-shield" },
        { name: "nbp-icon-user-slash" },
        { name: "nbp-icon-user-tag" },
        { name: "nbp-icon-user-tie" },
        { name: "nbp-icon-user-times" },
        { name: "nbp-icon-users" },
        { name: "nbp-icon-users-cog" },
        { name: "nbp-icon-users-slash" },
        { name: "nbp-icon-usps" },
        { name: "nbp-icon-ussunnah" },
        { name: "nbp-icon-utensil-spoon" },
        { name: "nbp-icon-utensils" },
        { name: "nbp-icon-vaadin" },
        { name: "nbp-icon-vector-square" },
        { name: "nbp-icon-venus" },
        { name: "nbp-icon-venus-double" },
        { name: "nbp-icon-venus-mars" },
        { name: "nbp-icon-vest" },
        { name: "nbp-icon-vest-patches" },
        { name: "nbp-icon-viacoin" },
        { name: "nbp-icon-viadeo" },
        { name: "nbp-icon-viadeo-square" },
        { name: "nbp-icon-vial" },
        { name: "nbp-icon-vials" },
        { name: "nbp-icon-viber" },
        { name: "nbp-icon-video" },
        { name: "nbp-icon-video-slash" },
        { name: "nbp-icon-vihara" },
        { name: "nbp-icon-vimeo" },
        { name: "nbp-icon-vimeo-square" },
        { name: "nbp-icon-vimeo-v" },
        { name: "nbp-icon-vine" },
        { name: "nbp-icon-virus" },
        { name: "nbp-icon-virus-slash" },
        { name: "nbp-icon-viruses" },
        { name: "nbp-icon-vk" },
        { name: "nbp-icon-vnv" },
        { name: "nbp-icon-voicemail" },
        { name: "nbp-icon-volleyball-ball" },
        { name: "nbp-icon-volume-down" },
        { name: "nbp-icon-volume-mute" },
        { name: "nbp-icon-volume-off" },
        { name: "nbp-icon-volume-up" },
        { name: "nbp-icon-vote-yea" },
        { name: "nbp-icon-vr-cardboard" },
        { name: "nbp-icon-vuejs" },
        { name: "nbp-icon-walking" },
        { name: "nbp-icon-wallet" },
        { name: "nbp-icon-warehouse" },
        { name: "nbp-icon-watchman-monitoring" },
        { name: "nbp-icon-water" },
        { name: "nbp-icon-wave-square" },
        { name: "nbp-icon-waze" },
        { name: "nbp-icon-weebly" },
        { name: "nbp-icon-weibo" },
        { name: "nbp-icon-weight" },
        { name: "nbp-icon-weight-hanging" },
        { name: "nbp-icon-weixin" },
        { name: "nbp-icon-whatsapp" },
        { name: "nbp-icon-whatsapp-square" },
        { name: "nbp-icon-wheelchair" },
        { name: "nbp-icon-whmcs" },
        { name: "nbp-icon-wifi" },
        { name: "nbp-icon-wikipedia-w" },
        { name: "nbp-icon-wind" },
        { name: "nbp-icon-window-close" },
        { name: "nbp-icon-window-maximize" },
        { name: "nbp-icon-window-minimize" },
        { name: "nbp-icon-window-restore" },
        { name: "nbp-icon-windows" },
        { name: "nbp-icon-wine-bottle" },
        { name: "nbp-icon-wine-glass" },
        { name: "nbp-icon-wine-glass-alt" },
        { name: "nbp-icon-wix" },
        { name: "nbp-icon-wizards-of-the-coast" },
        { name: "nbp-icon-wodu" },
        { name: "nbp-icon-wolf-pack-battalion" },
        { name: "nbp-icon-won-sign" },
        { name: "nbp-icon-wordpress" },
        { name: "nbp-icon-wordpress-simple" },
        { name: "nbp-icon-wpbeginner" },
        { name: "nbp-icon-wpexplorer" },
        { name: "nbp-icon-wpforms" },
        { name: "nbp-icon-wpressr" },
        { name: "nbp-icon-wrench" },
        { name: "nbp-icon-x-ray" },
        { name: "nbp-icon-xbox" },
        { name: "nbp-icon-xing" },
        { name: "nbp-icon-xing-square" },
        { name: "nbp-icon-y-combinator" },
        { name: "nbp-icon-yahoo" },
        { name: "nbp-icon-yammer" },
        { name: "nbp-icon-yandex" },
        { name: "nbp-icon-yandex-international" },
        { name: "nbp-icon-yarn" },
        { name: "nbp-icon-yelp" },
        { name: "nbp-icon-yen-sign" },
        { name: "nbp-icon-yin-yang" },
        { name: "nbp-icon-yoast" },
        { name: "nbp-icon-youtube" },
        { name: "nbp-icon-youtube-square" },
        { name: "nbp-icon-zhihu" },
      ],
    },
  };
}
